music/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new,:create,:show]
  resource :session, only: [:new,:create,:destroy]
  resources :bands 
  resources :albums 
  resources :tracks, only: [:create,:edit,:show,:update,:destroy]

  resources :albums, only: [] do
    resources :tracks, only: [:new]
  end

end

music/app/models/album.rb
class Album < ApplicationRecord
    validates :title, :yr, :band, presence: true

    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band 
end

music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true 
end

music/app/models/track.rb
class Track < ApplicationRecord
end

music/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :session_token, :password_digest, presence: true
    validates :email, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}
    attr_reader :password
    before_validation :ensure_session_token

    def self.find_by_credentials(email,password)
        user = User.find_by(email: email)
        
        if user && user.is_password?(password)
            return user 
        else 
            return nil 
        end
    
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        bcrypt_object = BCrypt::Password.new(self.password_digest)
        bcrypt_object.is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

    def generate_session_token
        token = SecureRandom.urlsafe_base64

        while User.exists?(session_token: token)
            token = SecureRandom.urlsafe_base64
        end

        token

    end

    def ensure_session_token
        self.session_token ||= generate_session_token
    end

end

music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action set_album, only: [:show,:edit,:update,:destroy]
    def set_album 
        @album ||= Album.find_by(id: params["id"])
    end

    def new 
        @album = Album.new
        render :new
    end

    def edit 
        render :edit 
    end

    def show 
        render :show 
    end

    def index 
        @albums = Album.all
        render :index
    end

    def destroy 
        if @album.destroy 
            redirect_to albums_url
        else 
            redirect_to album_url(@album.id)
    end

    def create 
        # Need: title, yr, band 
        @album = Album.new(album_params)

        if @album.save!
            redirect_to album_url(@album.id)
        else    
            redirect_to new_album_url 
        end
    end

    def update 
        old_album = @album
        @album = Album.new(album_params)
        if @album.save!
            redirect_to album_url(@album.id)
        else
            redirect_to edit_album_url 
        end
    end

    

    def album_params 
        params.require(:album).permit(:title,:yr,:band)
    end

end

music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#CRRLLL
protect_from_forgery with: :exception 
helper_method :current_user 


def current_user
    current_token = session[:session_token]
    @current_user ||= User.find_by(session_token: current_token)
end

def require_logged_in
    if !logged_in?
        redirect_to new_session_url
    end
end

def require_logged_out
    if logged_in?
       redirect_to new_session_url
    end
end

def logged_in?
    !!current_user
end

def login(user)
    session[:session_token] = user.reset_session_token!
end

def logout
    if logged_in?
        current_user.reset_session_token!
    end
    session[:session_token] = nil
    @current_user = nil
end 





end

music/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show,:edit,:update,:destroy]
    def set_band
        @band ||= Band.find_by(id: params["id"])
    end
    def new 
        @band = Band.new
        render :new 
    end

    def index 
        @band = Band.all 
        render :index
    end

    def edit 
        render :edit 
    end

    def show 
        render :show 
    end

    def create 
        @band = Band.new(band_params)

        if @band.save! 
            redirect_to band_url(@band.id)
        else
            redirect_to new_band_url
        end
    end

    def update 
        @band.name = params[:band][:name]
        if @band.save!
            redirect_to band_url(@band.id)
        else
            redirect_to edit_band_url(@band.id)
        end
    end

    def destroy 
        @band.destroy
        redirect_to bands_url
    end 



    def band_params
        params.require(:band).permit(:name)
    end


end

music/app/controllers/helpers/albums_helper.rb
module AlbumsHelper
end

music/app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

music/app/controllers/helpers/bands_helper.rb
module BandsHelper
end

music/app/controllers/helpers/session_helper.rb
module SessionHelper
end

music/app/controllers/helpers/users_helper.rb
module UsersHelper
end

music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
        @user = User.new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email],params[:user][:password])

        if user
            login(user)
            redirect_to user_url(user.id)
        else
            redirect_to new_session_url
        end

    end

    def destroy
        logout
        redirect_to new_session_url
    end

end

music/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new 
    end

    def create 
        user = User.new(strong_params)
        if user.save! 
            redirect_to user_url(user.id)
        else
            redirect_to new_userl_url
        end
    end

    def show
        @user = User.find_by(id: params["id"])
        render :show
    end


    def strong_params
        params.require(:user).permit(:email,:password)
    end
end

music/app/views/bands/edit.html.erb
<h1><%=@band.name%></h1>

<form action="<%=band_url(@band.id)%>" method="post">
<label for="name">Band Name: </label>
<input id="name" type="text" name ="band[name]">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<input type="Hidden" name="_method" value="Patch">
</form>

<form action="<%=band_url(@band.id)%>" method="post">
<input id="name" type="submit" value ="Delete Band">
<input type="Hidden" name="_method" value="Delete">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
</form>

music/app/views/bands/index.html.erb
<h1> All the bands! </h1>

<a href="<%=new_band_url%>">Create New Band </a>

<table>
    <tr>
        <th>Id </th>
        <th>Name </th>
    </tr>
    <%@band.each do |band|%>
    <tr>
        <td><%=band.id%></td>
        <td><a href="/bands/<%=band.id%>"><%=band.name%></a></td>
    </tr>
    <%end%>

</table>

        

music/app/views/bands/new.html.erb
<h1>New Band</h1>

<form action="/bands" method="post">
<label for="name">Band Name: </label>
<input id="name" type="text" name ="band[name]">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
</form>

music/app/views/bands/show.html.erb
<h1><%=@band.name%></h1>

<a href="/bands/<%=@band.id%>/edit">Edit Band </a>

<p> Albums will go here </p>

music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>
  <%if !!current_user%>
    <form action="/session" method ="post">
    <input id="logout" type ="submit" value ="Logout">
    <input type = "hidden" name="_method" value = "Delete">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    </form>
  <%else%>
    <a href="<%=new_session_url%>">Login Page</a>
    <br>
    <a href="<%=new_user_url%>">New User</a>
  <%end%>
  

  <body>
    <%= yield %>
  </body>
</html>

music/app/views/users/new.html.erb
<h1> New User <h2>

<form action="/users" method = "Post">
<label for="email"> Email: </label>
<input id ="email" type = "Text" name ="user[email]">
<label for="password"> Password: </label>
<input id ="password" type = "Password" name="user[password]">
<input id ="button" type = "submit" value = "Create New User">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
</form>

music/app/views/users/show.html.erb
<h1><%=@user.email%></h1>

<body>
<p>This works! </p>
</body>